"""Rigid-body attitude dynamics, control, and estimation (Milestone 1)."""

from attitude_sim.actuators import TorqueActuator, clip_torque, make_actuator
from attitude_sim.controls import (
    AttitudeLQR,
    LQRAttitudeController,
    PIDAttitudeController,
    design_attitude_lqr,
    make_controller,
    shape_pid_command,
    solve_care,
)
from attitude_sim.disturbances import (
    AerodynamicTorque,
    CircularOrbit,
    EnvironmentalTorques,
    GravityGradientTorque,
    OrbitState,
    ResidualDipoleTorque,
    SolarRadiationPressureTorque,
    aerodynamic_torque,
    gravity_gradient_torque,
    magnetic_dipole_torque,
    magnetic_field_body,
    srp_torque,
)
from attitude_sim.estimation import (
    ComplementaryFilter,
    InnovationLog,
    MultiplicativeEKF,
    make_estimator,
    triad_attitude,
)
from attitude_sim.mrp import (
    mrp_B,
    mrp_derivative,
    mrp_switch,
    mrp_to_quat,
    mrp_to_rotation,
    quat_to_mrp,
)
from attitude_sim.plant import (
    RigidBody,
    inertia_from_principal,
    inertial_torque,
    is_principal,
    principal_moments_and_axes,
    rk4_step,
    rkmk4_step,
    step_rigid_body,
    trapezoid_inertial_impulse,
    validate_inertia,
)
from attitude_sim.plots import attitude_error_mrp, plot_env_torque, plot_mrp_error
from attitude_sim.polhode import (
    SpinStability,
    energy_casimir,
    kinetic_energy,
    principal_spin_stability,
    sample_herpolhode,
    sample_polhode,
)
from attitude_sim.quaternions import (
    axis_angle_to_quat,
    geodesic_angle,
    quat_conjugate,
    quat_error,
    quat_multiply,
    quat_normalize,
    quat_to_euler321,
    quat_to_rotation,
)
from attitude_sim.scenarios import (
    SCENARIOS,
    make_hold_environmental_torques,
    scenario_catalog_text,
)
from attitude_sim.sim import SimConfig, SimLog, make_scenario_config, run_sim, run_slew

# Mahony is the complementary-filter implementation; keep both names public.
MahonyFilter = ComplementaryFilter

__all__ = [
    "SCENARIOS",
    "AerodynamicTorque",
    "AttitudeLQR",
    "CircularOrbit",
    "ComplementaryFilter",
    "EnvironmentalTorques",
    "GravityGradientTorque",
    "InnovationLog",
    "LQRAttitudeController",
    "MahonyFilter",
    "MultiplicativeEKF",
    "OrbitState",
    "PIDAttitudeController",
    "ResidualDipoleTorque",
    "RigidBody",
    "SimConfig",
    "SimLog",
    "SolarRadiationPressureTorque",
    "SpinStability",
    "TorqueActuator",
    "aerodynamic_torque",
    "attitude_error_mrp",
    "axis_angle_to_quat",
    "clip_torque",
    "design_attitude_lqr",
    "energy_casimir",
    "geodesic_angle",
    "gravity_gradient_torque",
    "inertia_from_principal",
    "inertial_torque",
    "is_principal",
    "kinetic_energy",
    "magnetic_dipole_torque",
    "magnetic_field_body",
    "make_actuator",
    "make_controller",
    "make_estimator",
    "make_hold_environmental_torques",
    "make_scenario_config",
    "mrp_B",
    "mrp_derivative",
    "mrp_switch",
    "mrp_to_quat",
    "mrp_to_rotation",
    "plot_env_torque",
    "plot_mrp_error",
    "principal_moments_and_axes",
    "principal_spin_stability",
    "quat_conjugate",
    "quat_error",
    "quat_multiply",
    "quat_normalize",
    "quat_to_euler321",
    "quat_to_mrp",
    "quat_to_rotation",
    "rk4_step",
    "rkmk4_step",
    "run_sim",
    "run_slew",
    "sample_herpolhode",
    "sample_polhode",
    "scenario_catalog_text",
    "shape_pid_command",
    "solve_care",
    "srp_torque",
    "step_rigid_body",
    "trapezoid_inertial_impulse",
    "triad_attitude",
    "validate_inertia",
]

__version__ = "0.1.0"
